### ISSUE TITLE
Prevent duplicate shortening

### ISSUE THREAD

**Issue by starfish1337** [lrstanley/links#12]
Links, by default, creates duplicate IDs for the same URL. that behaviour can be changed to look up if the URL is in the database, and return the corresponding short ID.

If a user does want new IDs, they should be able to create them by using an encryption string.

In short, any URL that does not have an encryption string, will always return the same ID. and in case the URL has an encryption string, it will return a new ID.

**Comment by lrstanley** [comment]
Same thing as the other issue, old version had this. I removed this functionality due to the new datastore being used, where we'd have to parse every single object to find a duplicate, which is a massive performance hit.

If we were to move away from BoltDB, to something like SQLite (worse general performance, but would easily allow this), this would be possible.

Likely won't fix as I don't feel like creating migration scripts and whatnot to do a migration from boltdb to sqlite, since this is a fairly simple project and not designed to have a bunch of functionality. Will keep it open just in case though.

**Comment by starfish1337** [comment]
I'm not sure about how databases work, but I just had a possibly very stupid idea that I wanted to share.

Would having 2 databases solve the limitation of BoltDB in this situation?

I mean, have one database (the existing one) which stores a value (the URL to be shortened) in an object ( the UUID )

and another database, which is the exact inverse of this : the URL to be shortened is the object and the UUID is the value.

so, to check for duplicates, Links has to query the second database only to parse the single object with the URL, and return it's corresponding value which would be the UUID.

I'm not sure about the performance impact that having 2 databases to query will have, and also understand that it means having twice the size of the intended database, but there still is some saving in space too, through the prevention of duplicate URLs.

**Comment by lrstanley** [comment]
I don't think two databases would help, it would be about 2x the data, likely. The best solution is to change DB's if the size is an issue, which, I don't think it's a huge issue. With links.wtf, I've got 1,772,907 links in the database as of making this post. That's about 675MB, which isn't crazy. Further note is that the way boltdb expands data on disk, it is going to use more disk space than it actually uses (e.g. if it's using 500MB, and it uses one byte over 500MB, it may allocate another 100MB for the future, but not use all of it).

If I'm feeling less lazy, I'll probably migrate to SQLite. DB probably won't be much smaller but querying will be easier, in addition to the features I'd like to add in https://github.com/lrstanley/links/issues/16.

**Comment by lrstanley** [comment]
Going to close this, as I don't think the feature is worth the effort involved to make the switch to SQLite, in addition to not enough usage. Though, if anyone else is interested in taking it on, feel free to submit a PR.
