### ISSUE TITLE
Enhance randomization

### ISSUE THREAD

**Issue by starfish1337** [lrstanley/links#13]
Links uses a 4 character set by default. therefore, the possible combinations are 62^4 = 14,776,336 (almost 14 million).

if the character set is increased to 6, for example, it increases to possible combinations to approximately 56 billion.

although having a six character ID is not ideally desirable, the default behaviour can be changed to exhaust the combinations with the current default character set, i.e., 4 characters, and then jump to 5 character set combinations, and then 6, and so on.

**Comment by lrstanley** [comment]
The old version of Links (which I wrote in python) had this. Not sure why I never re-added this functionality. Essentially, try and get a new uuid (default to 4), and if it takes X amount of times before we obtain a new uuid without collisions, then bump up to the next size. Will re-add when I get a chance.

**Comment by starfish1337** [comment]
with almost 15 million combinations possible, what would be your recommended value of X, so as to maximise the use of the lower size before jumping on to the next size, whilst at the same time, not spending too much time generating an available uuid?
