### ISSUE TITLE
Question : what's the purpose of this code here?

### ISSUE THREAD

**Issue by starfish1337** [lrstanley/links#15]
https://github.com/lrstanley/links/blob/01a24a5c1b6f1cde1387baf8784c536f66a6599a/http.go#L218:L221

**Comment by lrstanley** [comment]
Legacy method of providing a password, from the old python version of links.

**Comment by starfish1337** [comment]
Are there any other instances of code pertaining to the legacy python version of Links that can be removed if one doesn't want to maintain compatibility with the old code?

**Comment by lrstanley** [comment]
Sounds like a non-issue.
